name: Repo Visualizer
run-name: Making a diagram
on:
  push:
    branches:
      - main
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Repo Visualizer
          # You may pin to the exact commit or the version.
          # uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85
        uses: githubocto/repo-visualizer@0.9.1
        with:
          # A list of paths to exclude from the diagram, separated by commas. For example: dist,node_modules
          excluded_paths: "node_modules"
          # The directory (and its children) that you want to visualize in the diagram. Default: "" (repository root directory)
          root_path: "/todo-app"
          # Whether to push the new commit back to the repository. Must be true or false. Default: true
          should_push: false
          # If given, the name of an artifact to be created containing the diagram. Default: don't create an artifact.
          artifact_name: "diagram"
